version: '3'

services:
  api-gateway:
    build: './api-gateway'
    depends_on:
      - stories-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  stories-service:
    build: './stories-service'
    depends_on:
      - stories-service-db
    environment:
      - DB_URI=mysql://root:password@stories-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./stories-service:/opt/app

  stories-service-db:
    image: mysql:5.7.20
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: './users-service'
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    image: mysql:5.7.20
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 0.0.0.0:7201:3306